service: serverless-web-socket
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
custom:
  tableName: WebsocketUsers

functions:
  websocket-connect:
    handler: src/lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: src/lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-message:
    handler: src/lambdas/websockets/message.handler
    events:
      - websocket:
          route: message
  websocket-default:
    handler: src/lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default

resources:
  Resources:
    WebsocketUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
